# Generated by Django 3.0.6 on 2020-06-01 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mediamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_gif', models.FileField(blank=True, null=True, upload_to='mediafiles/gif/', verbose_name='Загрузка GIF')),
                ('media_video', models.FileField(blank=True, null=True, upload_to='mediafiles/video/', verbose_name='Загрузка Видео')),
                ('media_img', models.ImageField(blank=True, null=True, upload_to='mediafiles/img/', verbose_name='Загрузка Картинки')),
                ('medialink', models.CharField(blank=True, max_length=254, null=True, verbose_name='Ссылка на видео')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время загрузки')),
                ('filetype', models.CharField(choices=[('gif', 'Гифка'), ('video', 'Видео'), ('link', 'Ссылка на видео'), ('img', 'Картинка')], default='gif', max_length=254, verbose_name='Тип записи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
