# Generated by Django 3.0.7 on 2020-06-06 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', models.TextField(max_length=200, verbose_name='Описание')),
                ('file', models.FileField(upload_to='file/', verbose_name='Файл')),
                ('filetype', models.CharField(choices=[('gif', 'Гифка'), ('video', 'Видео'), ('img', 'Картинка')], default='img', max_length=254, verbose_name='Тип записи')),
                ('medialink', models.CharField(blank=True, max_length=254, null=True, verbose_name='Ссылка на видео')),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tags', models.ManyToManyField(related_name='memes', to='gifcol_app.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Загруженную запись',
                'verbose_name_plural': 'Загруженные записи',
            },
        ),
    ]
