# Generated by Django 3.0.6 on 2020-06-01 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifcol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediamodel',
            options={'verbose_name': 'загруженную запись', 'verbose_name_plural': 'Загруженные записи'},
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='author',
            field=models.ForeignKey(default='root', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='media_gif',
            field=models.FileField(blank=True, null=True, upload_to='gif/', verbose_name='Загрузка GIF'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='media_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Загрузка Картинки'),
        ),
        migrations.AlterField(
            model_name='mediamodel',
            name='media_video',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Загрузка Видео'),
        ),
    ]
