# Generated by Django 3.0.6 on 2020-06-04 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifcol_app', '0003_auto_20200603_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
