# Generated by Django 3.0.6 on 2020-06-04 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifcol_app', '0004_mediamodel_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
