# Generated by Django 3.0.6 on 2020-06-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifcol_app', '0005_mediamodel_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediamodel',
            name='like',
        ),
    ]
