# Generated by Django 3.0.6 on 2020-06-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifcol_app', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
