# Generated by Django 3.0.6 on 2020-06-05 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifcol_app', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userdesc',
            field=models.TextField(default='', max_length=250, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userwebsite',
            field=models.URLField(default='', verbose_name='Мой вебсайт'),
        ),
    ]
