# Generated by Django 3.0.6 on 2020-06-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifcol_app', '0010_auto_20200605_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'профили пользователей'},
        ),
    ]
