# Generated by Django 3.0.6 on 2020-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifcol_app', '0011_auto_20200605_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
